/* eslint-disable import/prefer-default-export */
export const keyBase = {
  eng: [
    [
      {
        code: 'Backquote',
        value: '`',
        valueShift: '~',
        keySpecial: '',
      },
      {
        code: 'Digit1',
        value: '1',
        valueShift: '!',
        keySpecial: '',
      },
      {
        code: 'Digit2',
        value: '2',
        valueShift: '@',
        keySpecial: '',
      },
      {
        code: 'Digit3',
        value: '3',
        valueShift: '#',
        keySpecial: '',
      },
      {
        code: 'Digit4',
        value: '4',
        valueShift: '$',
        keySpecial: '',
      },
      {
        code: 'Digit5',
        value: '5',
        valueShift: '%',
        keySpecial: '',
      },
      {
        code: 'Digit6',
        value: '6',
        valueShift: '^',
        keySpecial: '',
      },
      {
        code: 'Digit7',
        value: '7',
        valueShift: '&',
        keySpecial: '',
      },
      {
        code: 'Digit8',
        value: '8',
        valueShift: '*',
        keySpecial: '',
      },
      {
        code: 'Digit9',
        value: '9',
        valueShift: '(',
        keySpecial: '',
      },
      {
        code: 'Digit0',
        value: '0',
        valueShift: ')',
        keySpecial: '',
      },
      {
        code: 'Minus',
        value: '-',
        valueShift: '_',
        keySpecial: '',
      },
      {
        code: 'Equal',
        value: '=',
        valueShift: '+',
        keySpecial: '',
      },
      {
        code: 'Backspace',
        value: 'Backspace',
        valueShift: 'Backspace',
        keySpecial: 'Backspace',
      },
    ],
    [
      {
        code: 'Tab',
        value: 'Tab',
        valueShift: 'Tab',
        keySpecial: 'Tab',
      },
      {
        code: 'KeyQ',
        value: 'q',
        valueShift: 'Q',
        keySpecial: '',
      },
      {
        code: 'KeyW',
        value: 'w',
        valueShift: 'W',
        keySpecial: '',
      },
      {
        code: 'KeyE',
        value: 'e',
        valueShift: 'E',
        keySpecial: '',
      },
      {
        code: 'KeyR',
        value: 'r',
        valueShift: 'R',
        keySpecial: '',
      },
      {
        code: 'KeyT',
        value: 't',
        valueShift: 'T',
        keySpecial: '',
      },
      {
        code: 'KeyY',
        value: 'y',
        valueShift: 'Y',
        keySpecial: '',
      },
      {
        code: 'KeyU',
        value: 'u',
        valueShift: 'U',
        keySpecial: '',
      },
      {
        code: 'KeyI',
        value: 'i',
        valueShift: 'I',
        keySpecial: '',
      },
      {
        code: 'KeyO',
        value: 'o',
        valueShift: 'O',
        keySpecial: '',
      },
      {
        code: 'KeyP',
        value: 'p',
        valueShift: 'P',
        keySpecial: '',
      },
      {
        code: 'BracketLeft',
        value: '[',
        valueShift: '{',
        keySpecial: '',
      },
      {
        code: 'BracketRight',
        value: ']',
        valueShift: '}',
        keySpecial: '',
      },
      {
        code: 'Delete',
        value: 'Delete',
        valueShift: 'Delete',
        keySpecial: 'Delete',
      },
    ],
    [
      {
        code: 'CapsLock',
        value: 'CapsLock',
        valueShift: 'CapsLock',
        keySpecial: 'CapsLock',
      },
      {
        code: 'KeyA',
        value: 'a',
        valueShift: 'A',
        keySpecial: '',
      },
      {
        code: 'KeyS',
        value: 's',
        valueShift: 'S',
        keySpecial: '',
      },
      {
        code: 'KeyD',
        value: 'd',
        valueShift: 'D',
        keySpecial: '',
      },
      {
        code: 'KeyF',
        value: 'f',
        valueShift: 'F',
        keySpecial: '',
      },
      {
        code: 'KeyG',
        value: 'g',
        valueShift: 'G',
        keySpecial: '',
      },
      {
        code: 'KeyH',
        value: 'h',
        valueShift: 'H',
        keySpecial: '',
      },
      {
        code: 'KeyJ',
        value: 'j',
        valueShift: 'J',
        keySpecial: '',
      },
      {
        code: 'KeyK',
        value: 'k',
        valueShift: 'K',
        keySpecial: '',
      },
      {
        code: 'KeyL',
        value: 'l',
        valueShift: 'L',
        keySpecial: '',
      },
      {
        code: 'Semicolon',
        value: ';',
        valueShift: ':',
        keySpecial: '',
      },
      {
        code: 'Quote',
        value: "'",
        valueShift: '"',
        keySpecial: '',
      },
      {
        code: 'Enter',
        value: 'Enter',
        valueShift: 'Enter',
        keySpecial: 'Enter',
      },
    ],
    [
      {
        code: 'ShiftLeft',
        value: 'Shift',
        valueShift: 'Shift',
        keySpecial: 'ShiftLeft',
      },
      {
        code: 'IntlBackslash',
        value: '\\',
        valueShift: '|',
        keySpecial: '',
      },
      {
        code: 'KeyZ',
        value: 'z',
        valueShift: 'Z',
        keySpecial: '',
      },
      {
        code: 'KeyX',
        value: 'x',
        valueShift: 'X',
        keySpecial: '',
      },
      {
        code: 'KeyC',
        value: 'c',
        valueShift: 'C',
        keySpecial: '',
      },
      {
        code: 'KeyV',
        value: 'v',
        valueShift: 'V',
        keySpecial: '',
      },
      {
        code: 'KeyB',
        value: 'b',
        valueShift: 'B',
        keySpecial: '',
      },
      {
        code: 'KeyN',
        value: 'n',
        valueShift: 'N',
        keySpecial: '',
      },
      {
        code: 'KeyM',
        value: 'm',
        valueShift: 'M',
        keySpecial: '',
      },
      {
        code: 'Comma',
        value: ',',
        valueShift: '<',
        keySpecial: '',
      },
      {
        code: 'Period',
        value: '.',
        valueShift: '>',
        keySpecial: '',
      },
      {
        code: 'Slash',
        value: '/',
        valueShift: '?',
        keySpecial: '',
      },
      {
        code: 'ArrowUp',
        value: '▲',
        valueShift: '▲',
        keySpecial: '',
      },
      {
        code: 'ShiftRight',
        value: 'Shift',
        valueShift: 'Shift',
        keySpecial: 'ShiftRight',
      },
    ],
    [
      {
        code: 'ControlLeft',
        value: 'Ctrl',
        valueShift: 'Ctrl',
        keySpecial: 'CtrlLeft',
      },
      {
        code: 'MetaLeft',
        value: 'Win',
        valueShift: 'Win',
        keySpecial: 'Win',
      },
      {
        code: 'AltLeft',
        value: 'Alt',
        valueShift: 'Alt',
        keySpecial: 'AltLeft',
      },
      {
        code: 'Space',
        value: ' ',
        valueShift: ' ',
        keySpecial: 'Space',
      },
      {
        code: 'AltRight',
        value: 'Alt',
        valueShift: 'Alt',
        keySpecial: 'AltRight',
      },
      {
        code: 'ControlRight',
        value: 'Ctrl',
        valueShift: 'Ctrl',
        keySpecial: 'CtrlRight',
      },
      {
        code: 'Language',
        value: 'ENG',
        valueShift: 'ENG',
        keySpecial: 'Language',
      },
      {
        code: 'ArrowLeft',
        value: '◄',
        valueShift: '◄',
        keySpecial: '',
      },
      {
        code: 'ArrowDown',
        value: '▼',
        valueShift: '▼',
        keySpecial: '',
      },
      {
        code: 'ArrowRight',
        value: '►',
        valueShift: '►',
        keySpecial: '',
      },
    ],
  ],
  ru: [
    [
      {
        code: 'Backquote',
        value: 'ё',
        valueShift: 'Ё',
        keySpecial: '',
      },
      {
        code: 'Digit1',
        value: '1',
        valueShift: '!',
        keySpecial: '',
      },
      {
        code: 'Digit2',
        value: '2',
        valueShift: '"',
        keySpecial: '',
      },
      {
        code: 'Digit3',
        value: '3',
        valueShift: '№',
        keySpecial: '',
      },
      {
        code: 'Digit4',
        value: '4',
        valueShift: ';',
        keySpecial: '',
      },
      {
        code: 'Digit5',
        value: '5',
        valueShift: '%',
        keySpecial: '',
      },
      {
        code: 'Digit6',
        value: '6',
        valueShift: ':',
        keySpecial: '',
      },
      {
        code: 'Digit7',
        value: '7',
        valueShift: '?',
        keySpecial: '',
      },
      {
        code: 'Digit8',
        value: '8',
        valueShift: '*',
        keySpecial: '',
      },
      {
        code: 'Digit9',
        value: '9',
        valueShift: '(',
        keySpecial: '',
      },
      {
        code: 'Digit0',
        value: '0',
        valueShift: ')',
        keySpecial: '',
      },
      {
        code: 'Minus',
        value: '-',
        valueShift: '_',
        keySpecial: '',
      },
      {
        code: 'Equal',
        value: '=',
        valueShift: '+',
        keySpecial: '',
      },
      {
        code: 'Backspace',
        value: 'Backspace',
        valueShift: 'Backspace',
        keySpecial: 'Backspace',
      },
    ],
    [
      {
        code: 'Tab',
        value: 'Tab',
        valueShift: 'Tab',
        keySpecial: 'Tab',
      },
      {
        code: 'KeyQ',
        value: 'й',
        valueShift: 'Й',
        keySpecial: '',
      },
      {
        code: 'KeyW',
        value: 'ц',
        valueShift: 'Ц',
        keySpecial: '',
      },
      {
        code: 'KeyE',
        value: 'у',
        valueShift: 'У',
        keySpecial: '',
      },
      {
        code: 'KeyR',
        value: 'к',
        valueShift: 'К',
        keySpecial: '',
      },
      {
        code: 'KeyT',
        value: 'е',
        valueShift: 'Е',
        keySpecial: '',
      },
      {
        code: 'KeyY',
        value: 'н',
        valueShift: 'Н',
        keySpecial: '',
      },
      {
        code: 'KeyU',
        value: 'г',
        valueShift: 'Г',
        keySpecial: '',
      },
      {
        code: 'KeyI',
        value: 'ш',
        valueShift: 'Ш',
        keySpecial: '',
      },
      {
        code: 'KeyO',
        value: 'щ',
        valueShift: 'Щ',
        keySpecial: '',
      },
      {
        code: 'KeyP',
        value: 'з',
        valueShift: 'З',
        keySpecial: '',
      },
      {
        code: 'BracketLeft',
        value: 'х',
        valueShift: 'Х',
        keySpecial: '',
      },
      {
        code: 'BracketRight',
        value: 'ъ',
        valueShift: 'Ъ',
        keySpecial: '',
      },
      {
        code: 'Delete',
        value: 'Delete',
        valueShift: 'Delete',
        keySpecial: 'Delete',
      },
    ],
    [
      {
        code: 'CapsLock',
        value: 'CapsLock',
        valueShift: 'CapsLock',
        keySpecial: 'CapsLock',
      },
      {
        code: 'KeyA',
        value: 'ф',
        valueShift: 'Ф',
        keySpecial: '',
      },
      {
        code: 'KeyS',
        value: 'ы',
        valueShift: 'Ы',
        keySpecial: '',
      },
      {
        code: 'KeyD',
        value: 'в',
        valueShift: 'В',
        keySpecial: '',
      },
      {
        code: 'KeyF',
        value: 'а',
        valueShift: 'А',
        keySpecial: '',
      },
      {
        code: 'KeyG',
        value: 'п',
        valueShift: 'П',
        keySpecial: '',
      },
      {
        code: 'KeyH',
        value: 'р',
        valueShift: 'Р',
        keySpecial: '',
      },
      {
        code: 'KeyJ',
        value: 'о',
        valueShift: 'О',
        keySpecial: '',
      },
      {
        code: 'KeyK',
        value: 'л',
        valueShift: 'Л',
        keySpecial: '',
      },
      {
        code: 'KeyL',
        value: 'д',
        valueShift: 'Д',
        keySpecial: '',
      },
      {
        code: 'Semicolon',
        value: 'ж',
        valueShift: 'Ж',
        keySpecial: '',
      },
      {
        code: 'Quote',
        value: 'э',
        valueShift: 'Э',
        keySpecial: '',
      },
      {
        code: 'Enter',
        value: 'Enter',
        valueShift: 'Enter',
        keySpecial: 'Enter',
      },
    ],
    [
      {
        code: 'ShiftLeft',
        value: 'Shift',
        valueShift: 'Shift',
        keySpecial: 'ShiftLeft',
      },
      {
        code: 'IntlBackslash',
        value: '\\',
        valueShift: '/',
        keySpecial: '',
      },
      {
        code: 'KeyZ',
        value: 'я',
        valueShift: 'Я',
        keySpecial: '',
      },
      {
        code: 'KeyX',
        value: 'ч',
        valueShift: 'Ч',
        keySpecial: '',
      },
      {
        code: 'KeyC',
        value: 'с',
        valueShift: 'С',
        keySpecial: '',
      },
      {
        code: 'KeyV',
        value: 'м',
        valueShift: 'М',
        keySpecial: '',
      },
      {
        code: 'KeyB',
        value: 'и',
        valueShift: 'И',
        keySpecial: '',
      },
      {
        code: 'KeyN',
        value: 'т',
        valueShift: 'Т',
        keySpecial: '',
      },
      {
        code: 'KeyM',
        value: 'ь',
        valueShift: 'Ь',
        keySpecial: '',
      },
      {
        code: 'Comma',
        value: 'б',
        valueShift: 'Б',
        keySpecial: '',
      },
      {
        code: 'Period',
        value: 'ю',
        valueShift: 'Ю',
        keySpecial: '',
      },
      {
        code: 'Slash',
        value: '.',
        valueShift: ',',
        keySpecial: '',
      },
      {
        code: 'ArrowUp',
        value: '▲',
        valueShift: '▲',
        keySpecial: '',
      },
      {
        code: 'ShiftRight',
        value: 'Shift',
        valueShift: 'Shift',
        keySpecial: 'ShiftRight',
      },
    ],
    [
      {
        code: 'ControlLeft',
        value: 'Ctrl',
        valueShift: 'Ctrl',
        keySpecial: 'CtrlLeft',
      },
      {
        code: 'MetaLeft',
        value: 'Win',
        valueShift: 'Win',
        keySpecial: 'Win',
      },
      {
        code: 'AltLeft',
        value: 'Alt',
        valueShift: 'Alt',
        keySpecial: 'AltLeft',
      },
      {
        code: 'Space',
        value: ' ',
        valueShift: ' ',
        keySpecial: 'Space',
      },
      {
        code: 'AltRight',
        value: 'Alt',
        valueShift: 'Alt',
        keySpecial: 'AltRight',
      },
      {
        code: 'ControlRight',
        value: 'Ctrl',
        valueShift: 'Ctrl',
        keySpecial: 'CtrlRight',
      },
      {
        code: 'Language',
        value: 'RU',
        valueShift: 'RU',
        keySpecial: 'Language',
      },
      {
        code: 'ArrowLeft',
        value: '◄',
        valueShift: '◄',
        keySpecial: '',
      },
      {
        code: 'ArrowDown',
        value: '▼',
        valueShift: '▼',
        keySpecial: '',
      },
      {
        code: 'ArrowRight',
        value: '►',
        valueShift: '►',
        keySpecial: '',
      },
    ],
  ],
};
